// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 18 Jun 2025 22:33:09 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <gnumake.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// gmk_func_ptr_4ecc07b6 is a proxy for callback gmk_func_ptr.
char* gmk_func_ptr_4ecc07b6(char* nm, unsigned int argc, char** argv);

