// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 18 Jun 2025 20:58:18 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

char* gmk_func_ptr_4ecc07b6(char* nm, unsigned int argc, char** argv) {
	return funcPtr4ECC07B6(nm, argc, argv);
}

