// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 18 Jun 2025 21:08:29 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package gnumake

/*
#include <gnumake.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// FileLocation as declared in include/gnumake.h:27
type FileLocation struct {
	FileName       []byte
	LineNumber     uint64
	refe443217c    *C.gmk_floc
	allocse443217c interface{}
}

// FuncPtr type as declared in include/gnumake.h:29
type FuncPtr func(nm string, argc uint32, argv [][]byte) []byte
